//////////////////////////////////////////////////////////////////////////////////////////////
// DO NOT MODIFY THIS FILE                                                                  //
// This file is automatically generated by ZenStack CLI and should not be manually updated. //
//////////////////////////////////////////////////////////////////////////////////////////////

/* eslint-disable */

import { type SchemaType as $Schema } from "./schema";
import type { FindManyArgs as $FindManyArgs, FindUniqueArgs as $FindUniqueArgs, FindFirstArgs as $FindFirstArgs, CreateArgs as $CreateArgs, CreateManyArgs as $CreateManyArgs, CreateManyAndReturnArgs as $CreateManyAndReturnArgs, UpdateArgs as $UpdateArgs, UpdateManyArgs as $UpdateManyArgs, UpdateManyAndReturnArgs as $UpdateManyAndReturnArgs, UpsertArgs as $UpsertArgs, DeleteArgs as $DeleteArgs, DeleteManyArgs as $DeleteManyArgs, CountArgs as $CountArgs, AggregateArgs as $AggregateArgs, GroupByArgs as $GroupByArgs, WhereInput as $WhereInput, SelectInput as $SelectInput, IncludeInput as $IncludeInput, OmitInput as $OmitInput, ClientOptions as $ClientOptions } from "@zenstackhq/orm";
import type { SimplifiedModelResult as $SimplifiedModelResult, SelectIncludeOmit as $SelectIncludeOmit } from "@zenstackhq/orm";
export type PlainJsonFindManyArgs = $FindManyArgs<$Schema, "PlainJson">;
export type PlainJsonFindUniqueArgs = $FindUniqueArgs<$Schema, "PlainJson">;
export type PlainJsonFindFirstArgs = $FindFirstArgs<$Schema, "PlainJson">;
export type PlainJsonCreateArgs = $CreateArgs<$Schema, "PlainJson">;
export type PlainJsonCreateManyArgs = $CreateManyArgs<$Schema, "PlainJson">;
export type PlainJsonCreateManyAndReturnArgs = $CreateManyAndReturnArgs<$Schema, "PlainJson">;
export type PlainJsonUpdateArgs = $UpdateArgs<$Schema, "PlainJson">;
export type PlainJsonUpdateManyArgs = $UpdateManyArgs<$Schema, "PlainJson">;
export type PlainJsonUpdateManyAndReturnArgs = $UpdateManyAndReturnArgs<$Schema, "PlainJson">;
export type PlainJsonUpsertArgs = $UpsertArgs<$Schema, "PlainJson">;
export type PlainJsonDeleteArgs = $DeleteArgs<$Schema, "PlainJson">;
export type PlainJsonDeleteManyArgs = $DeleteManyArgs<$Schema, "PlainJson">;
export type PlainJsonCountArgs = $CountArgs<$Schema, "PlainJson">;
export type PlainJsonAggregateArgs = $AggregateArgs<$Schema, "PlainJson">;
export type PlainJsonGroupByArgs = $GroupByArgs<$Schema, "PlainJson">;
export type PlainJsonWhereInput = $WhereInput<$Schema, "PlainJson">;
export type PlainJsonSelect = $SelectInput<$Schema, "PlainJson">;
export type PlainJsonInclude = $IncludeInput<$Schema, "PlainJson">;
export type PlainJsonOmit = $OmitInput<$Schema, "PlainJson">;
export type PlainJsonGetPayload<Args extends $SelectIncludeOmit<$Schema, "PlainJson", true>, Options extends $ClientOptions<$Schema> = $ClientOptions<$Schema>> = $SimplifiedModelResult<$Schema, "PlainJson", Options, Args>;
