//////////////////////////////////////////////////////////////////////////////////////////////
// DO NOT MODIFY THIS FILE                                                                  //
// This file is automatically generated by ZenStack CLI and should not be manually updated. //
//////////////////////////////////////////////////////////////////////////////////////////////

/* eslint-disable */

import { type SchemaDef, ExpressionUtils } from "@zenstackhq/orm/schema";
const _schema = {
    provider: {
        type: "sqlite"
    },
    models: {
        Foo: {
            name: "Foo",
            fields: {
                id: {
                    name: "id",
                    type: "Int",
                    id: true,
                    attributes: [{ name: "@id" }, { name: "@default", args: [{ name: "value", value: ExpressionUtils.call("autoincrement") }] }],
                    default: ExpressionUtils.call("autoincrement")
                },
                data: {
                    name: "data",
                    type: "Json"
                },
                data1: {
                    name: "data1",
                    type: "Json",
                    optional: true
                }
            },
            idFields: ["id"],
            uniqueFields: {
                id: { type: "Int" }
            }
        }
    },
    plugins: {}
} as const satisfies SchemaDef;
type Schema = typeof _schema & {
    __brand?: "schema";
};
export const schema: Schema = _schema;
export type SchemaType = Schema;
