packages:
    - packages/**
    - samples/**
    - tests/**
catalog:
    kysely: ^0.27.6
    zod: ^3.25.0 || ^4.0.0
    prisma: ^6.10.0
    langium: 3.5.0
    langium-cli: 3.5.0
    ts-pattern: ^5.7.1
    typescript: ^5.8.0
    '@types/node': ^20.17.24
    tmp: ^0.2.3
    '@types/tmp': ^0.2.6
    'zod-validation-error': ^4.0.1
    'better-sqlite3': ^12.2.0
    'pg': ^8.13.1
