packages:
    - packages/**
    - samples/**
    - tests/**
catalog:
    kysely: ~0.28.8
    zod: ^4.0.0
    prisma: ^6.19.0
    langium: 3.5.0
    langium-cli: 3.5.0
    ts-pattern: ^5.7.1
    typescript: ^5.8.0
    '@types/node': ^20.19.0
    tmp: ^0.2.3
    '@types/tmp': ^0.2.6
    'zod-validation-error': ^4.0.1
    'better-sqlite3': ^12.2.0
    '@types/better-sqlite3': ^7.6.13
    'pg': ^8.13.1
    'sql.js': ^1.13.0
    'decimal.js': '^10.4.3'
    react: 19.2.0
    '@types/react': 19.2.0
    react-dom: 19.2.0
    '@types/react-dom': 19.2.0
    '@tanstack/react-query': 5.90.6
    'next': 16.0.1
    'vue': 3.5.22
    'svelte': 5.43.3
