//////////////////////////////////////////////////////////////////////////////////////////////
// DO NOT MODIFY THIS FILE                                                                  //
// This file is automatically generated by ZenStack CLI and should not be manually updated. //
//////////////////////////////////////////////////////////////////////////////////////////////

/* eslint-disable */

import { type ModelResult } from "@zenstackhq/runtime";
import { schema } from "./schema";
export type Schema = typeof schema;
/**
 * User model
 *
 * Represents a user of the blog.
 */
export type User = ModelResult<Schema, "User">;
/**
 * Profile model
 */
export type Profile = ModelResult<Schema, "Profile">;
/**
 * Post model
 */
export type Post = ModelResult<Schema, "Post">;
/**
 * User roles
 */
export const Role = schema.enums.Role;
/**
 * User roles
 */
export type Role = (typeof Role)[keyof typeof Role];
