//////////////////////////////////////////////////////////////////////////////////////////////
// DO NOT MODIFY THIS FILE                                                                  //
// This file is automatically generated by ZenStack CLI and should not be manually updated. //
//////////////////////////////////////////////////////////////////////////////////////////////

/* eslint-disable */

import { type SchemaDef } from "@zenstackhq/orm/schema";
const _schema = {
    provider: {
        type: "sqlite"
    },
    models: {
        Foo: {
            name: "Foo",
            fields: {
                id: {
                    name: "id",
                    type: "Int",
                    id: true,
                    attributes: [{ name: "@id" }]
                }
            },
            idFields: ["id"],
            uniqueFields: {
                id: { type: "Int" }
            }
        }
    },
    typeDefs: {
        Permission: {
            name: "Permission",
            fields: {
                actionCode: {
                    name: "actionCode",
                    type: "String"
                }
            }
        },
        Auth: {
            name: "Auth",
            fields: {
                id: {
                    name: "id",
                    type: "Int",
                    attributes: [{ name: "@id" }]
                },
                name: {
                    name: "name",
                    type: "String"
                },
                permissions: {
                    name: "permissions",
                    type: "Permission",
                    array: true
                },
                role: {
                    name: "role",
                    type: "String"
                }
            },
            attributes: [
                { name: "@@auth" }
            ]
        }
    },
    authType: "Auth",
    plugins: {}
} as const satisfies SchemaDef;
type Schema = typeof _schema & {
    __brand?: "schema";
};
export const schema: Schema = _schema;
export type SchemaType = Schema;
