//////////////////////////////////////////////////////////////////////////////////////////////
// DO NOT MODIFY THIS FILE                                                                  //
// This file is automatically generated by ZenStack CLI and should not be manually updated. //
//////////////////////////////////////////////////////////////////////////////////////////////

/* eslint-disable */

import { type SchemaDef, ExpressionUtils } from "@zenstackhq/orm/schema";
export class SchemaType implements SchemaDef {
    provider = {
        type: "sqlite"
    } as const;
    models = {
        User: {
            name: "User",
            fields: {
                id: {
                    name: "id",
                    type: "Int",
                    id: true,
                    attributes: [{ name: "@id" }, { name: "@default", args: [{ name: "value", value: ExpressionUtils.call("autoincrement") }] }],
                    default: ExpressionUtils.call("autoincrement")
                },
                name: {
                    name: "name",
                    type: "String"
                },
                role: {
                    name: "role",
                    type: "Role"
                }
            },
            idFields: ["id"],
            uniqueFields: {
                id: { type: "Int" }
            }
        }
    } as const;
    typeDefs = {
        Overview: {
            name: "Overview",
            fields: {
                userIds: {
                    name: "userIds",
                    type: "Int",
                    array: true
                },
                total: {
                    name: "total",
                    type: "Int"
                },
                roles: {
                    name: "roles",
                    type: "Role",
                    array: true
                },
                meta: {
                    name: "meta",
                    type: "Json",
                    optional: true
                }
            }
        }
    } as const;
    enums = {
        Role: {
            values: {
                ADMIN: "ADMIN",
                USER: "USER"
            }
        }
    } as const;
    authType = "User" as const;
    procedures = {
        getUser: {
            params: [
                { name: "id", type: "Int" }
            ] as [
                id: {
                    "name": "id";
                    "type": "Int";
                }
            ],
            returnType: "User"
        },
        listUsers: {
            params: [] as [
            ],
            returnType: "User",
            returnArray: true
        },
        findByIds: {
            params: [
                { name: "ids", array: true, type: "Int" }
            ] as [
                ids: {
                    "name": "ids";
                    "type": "Int";
                    "array": true;
                }
            ],
            returnType: "User",
            returnArray: true
        },
        overview: {
            params: [] as [
            ],
            returnType: "Overview"
        },
        getRole: {
            params: [] as [
            ],
            returnType: "Role"
        },
        getRoles: {
            params: [] as [
            ],
            returnType: "Role",
            returnArray: true
        },
        getNull: {
            params: [] as [
            ],
            returnType: "Null"
        },
        getVoid: {
            params: [] as [
            ],
            returnType: "Void"
        },
        getUndefined: {
            params: [] as [
            ],
            returnType: "Undefined"
        },
        greet: {
            params: [
                { name: "name", optional: true, type: "String" }
            ] as [
                name: {
                    "name": "name";
                    "type": "String";
                    "optional": true;
                }
            ],
            returnType: "String"
        },
        echoJson: {
            params: [
                { name: "payload", type: "Json" }
            ] as [
                payload: {
                    "name": "payload";
                    "type": "Json";
                }
            ],
            returnType: "Json"
        },
        echoBytes: {
            params: [
                { name: "payload", type: "Bytes" }
            ] as [
                payload: {
                    "name": "payload";
                    "type": "Bytes";
                }
            ],
            returnType: "Bytes"
        }
    } as const;
    plugins = {};
}
export const schema = new SchemaType();
