//////////////////////////////////////////////////////////////////////////////////////////////
// DO NOT MODIFY THIS FILE                                                                  //
// This file is automatically generated by ZenStack CLI and should not be manually updated. //
//////////////////////////////////////////////////////////////////////////////////////////////

/* eslint-disable */

import { type SchemaType as $Schema } from "./schema";
import type { FindManyArgs as $FindManyArgs, FindUniqueArgs as $FindUniqueArgs, FindFirstArgs as $FindFirstArgs, ExistsArgs as $ExistsArgs, CreateArgs as $CreateArgs, CreateManyArgs as $CreateManyArgs, CreateManyAndReturnArgs as $CreateManyAndReturnArgs, UpdateArgs as $UpdateArgs, UpdateManyArgs as $UpdateManyArgs, UpdateManyAndReturnArgs as $UpdateManyAndReturnArgs, UpsertArgs as $UpsertArgs, DeleteArgs as $DeleteArgs, DeleteManyArgs as $DeleteManyArgs, CountArgs as $CountArgs, AggregateArgs as $AggregateArgs, GroupByArgs as $GroupByArgs, WhereInput as $WhereInput, SelectInput as $SelectInput, IncludeInput as $IncludeInput, OmitInput as $OmitInput, QueryOptions as $QueryOptions } from "@zenstackhq/orm";
import type { SimplifiedPlainResult as $Result, SelectIncludeOmit as $SelectIncludeOmit } from "@zenstackhq/orm";
export type InternalChatFindManyArgs = $FindManyArgs<$Schema, "InternalChat">;
export type InternalChatFindUniqueArgs = $FindUniqueArgs<$Schema, "InternalChat">;
export type InternalChatFindFirstArgs = $FindFirstArgs<$Schema, "InternalChat">;
export type InternalChatExistsArgs = $ExistsArgs<$Schema, "InternalChat">;
export type InternalChatCreateArgs = $CreateArgs<$Schema, "InternalChat">;
export type InternalChatCreateManyArgs = $CreateManyArgs<$Schema, "InternalChat">;
export type InternalChatCreateManyAndReturnArgs = $CreateManyAndReturnArgs<$Schema, "InternalChat">;
export type InternalChatUpdateArgs = $UpdateArgs<$Schema, "InternalChat">;
export type InternalChatUpdateManyArgs = $UpdateManyArgs<$Schema, "InternalChat">;
export type InternalChatUpdateManyAndReturnArgs = $UpdateManyAndReturnArgs<$Schema, "InternalChat">;
export type InternalChatUpsertArgs = $UpsertArgs<$Schema, "InternalChat">;
export type InternalChatDeleteArgs = $DeleteArgs<$Schema, "InternalChat">;
export type InternalChatDeleteManyArgs = $DeleteManyArgs<$Schema, "InternalChat">;
export type InternalChatCountArgs = $CountArgs<$Schema, "InternalChat">;
export type InternalChatAggregateArgs = $AggregateArgs<$Schema, "InternalChat">;
export type InternalChatGroupByArgs = $GroupByArgs<$Schema, "InternalChat">;
export type InternalChatWhereInput = $WhereInput<$Schema, "InternalChat">;
export type InternalChatSelect = $SelectInput<$Schema, "InternalChat">;
export type InternalChatInclude = $IncludeInput<$Schema, "InternalChat">;
export type InternalChatOmit = $OmitInput<$Schema, "InternalChat">;
export type InternalChatGetPayload<Args extends $SelectIncludeOmit<$Schema, "InternalChat", true>, Options extends $QueryOptions<$Schema> = $QueryOptions<$Schema>> = $Result<$Schema, "InternalChat", Args, Options>;
export type MessageFindManyArgs = $FindManyArgs<$Schema, "Message">;
export type MessageFindUniqueArgs = $FindUniqueArgs<$Schema, "Message">;
export type MessageFindFirstArgs = $FindFirstArgs<$Schema, "Message">;
export type MessageExistsArgs = $ExistsArgs<$Schema, "Message">;
export type MessageCreateArgs = $CreateArgs<$Schema, "Message">;
export type MessageCreateManyArgs = $CreateManyArgs<$Schema, "Message">;
export type MessageCreateManyAndReturnArgs = $CreateManyAndReturnArgs<$Schema, "Message">;
export type MessageUpdateArgs = $UpdateArgs<$Schema, "Message">;
export type MessageUpdateManyArgs = $UpdateManyArgs<$Schema, "Message">;
export type MessageUpdateManyAndReturnArgs = $UpdateManyAndReturnArgs<$Schema, "Message">;
export type MessageUpsertArgs = $UpsertArgs<$Schema, "Message">;
export type MessageDeleteArgs = $DeleteArgs<$Schema, "Message">;
export type MessageDeleteManyArgs = $DeleteManyArgs<$Schema, "Message">;
export type MessageCountArgs = $CountArgs<$Schema, "Message">;
export type MessageAggregateArgs = $AggregateArgs<$Schema, "Message">;
export type MessageGroupByArgs = $GroupByArgs<$Schema, "Message">;
export type MessageWhereInput = $WhereInput<$Schema, "Message">;
export type MessageSelect = $SelectInput<$Schema, "Message">;
export type MessageInclude = $IncludeInput<$Schema, "Message">;
export type MessageOmit = $OmitInput<$Schema, "Message">;
export type MessageGetPayload<Args extends $SelectIncludeOmit<$Schema, "Message", true>, Options extends $QueryOptions<$Schema> = $QueryOptions<$Schema>> = $Result<$Schema, "Message", Args, Options>;
export type MediaFindManyArgs = $FindManyArgs<$Schema, "Media">;
export type MediaFindUniqueArgs = $FindUniqueArgs<$Schema, "Media">;
export type MediaFindFirstArgs = $FindFirstArgs<$Schema, "Media">;
export type MediaExistsArgs = $ExistsArgs<$Schema, "Media">;
export type MediaCreateArgs = $CreateArgs<$Schema, "Media">;
export type MediaCreateManyArgs = $CreateManyArgs<$Schema, "Media">;
export type MediaCreateManyAndReturnArgs = $CreateManyAndReturnArgs<$Schema, "Media">;
export type MediaUpdateArgs = $UpdateArgs<$Schema, "Media">;
export type MediaUpdateManyArgs = $UpdateManyArgs<$Schema, "Media">;
export type MediaUpdateManyAndReturnArgs = $UpdateManyAndReturnArgs<$Schema, "Media">;
export type MediaUpsertArgs = $UpsertArgs<$Schema, "Media">;
export type MediaDeleteArgs = $DeleteArgs<$Schema, "Media">;
export type MediaDeleteManyArgs = $DeleteManyArgs<$Schema, "Media">;
export type MediaCountArgs = $CountArgs<$Schema, "Media">;
export type MediaAggregateArgs = $AggregateArgs<$Schema, "Media">;
export type MediaGroupByArgs = $GroupByArgs<$Schema, "Media">;
export type MediaWhereInput = $WhereInput<$Schema, "Media">;
export type MediaSelect = $SelectInput<$Schema, "Media">;
export type MediaInclude = $IncludeInput<$Schema, "Media">;
export type MediaOmit = $OmitInput<$Schema, "Media">;
export type MediaGetPayload<Args extends $SelectIncludeOmit<$Schema, "Media", true>, Options extends $QueryOptions<$Schema> = $QueryOptions<$Schema>> = $Result<$Schema, "Media", Args, Options>;
