//////////////////////////////////////////////////////////////////////////////////////////////
// DO NOT MODIFY THIS FILE                                                                  //
// This file is automatically generated by ZenStack CLI and should not be manually updated. //
//////////////////////////////////////////////////////////////////////////////////////////////

/* eslint-disable */

import { type SchemaDef, ExpressionUtils } from "@zenstackhq/orm/schema";
const _schema = {
    provider: {
        type: "sqlite"
    },
    models: {
        User: {
            name: "User",
            fields: {
                id: {
                    name: "id",
                    type: "String",
                    id: true,
                    default: ExpressionUtils.call("cuid")
                },
                createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    default: ExpressionUtils.call("now")
                },
                updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    updatedAt: true
                },
                email: {
                    name: "email",
                    type: "String",
                    unique: true
                },
                name: {
                    name: "name",
                    type: "String",
                    optional: true
                },
                posts: {
                    name: "posts",
                    type: "Post",
                    array: true,
                    relation: { opposite: "author" }
                }
            },
            idFields: ["id"],
            uniqueFields: {
                id: { type: "String" },
                email: { type: "String" }
            }
        },
        Post: {
            name: "Post",
            fields: {
                id: {
                    name: "id",
                    type: "String",
                    id: true,
                    default: ExpressionUtils.call("cuid")
                },
                createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    default: ExpressionUtils.call("now")
                },
                updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    updatedAt: true
                },
                title: {
                    name: "title",
                    type: "String"
                },
                published: {
                    name: "published",
                    type: "Boolean",
                    default: false
                },
                author: {
                    name: "author",
                    type: "User",
                    relation: { opposite: "posts", fields: ["authorId"], references: ["id"], onUpdate: "Cascade", onDelete: "Cascade" }
                },
                authorId: {
                    name: "authorId",
                    type: "String",
                    foreignKeyFor: [
                        "author"
                    ]
                }
            },
            idFields: ["id"],
            uniqueFields: {
                id: { type: "String" }
            }
        }
    },
    authType: "User",
    plugins: {}
} as const satisfies SchemaDef;
type Schema = typeof _schema & {
    __brand?: "schema";
};
export const schema: Schema = _schema;
export type SchemaType = Schema;
