//////////////////////////////////////////////////////////////////////////////////////////////
// DO NOT MODIFY THIS FILE                                                                  //
// This file is automatically generated by ZenStack CLI and should not be manually updated. //
//////////////////////////////////////////////////////////////////////////////////////////////

/* eslint-disable */

import { type SchemaDef } from "@zenstackhq/orm/schema";
export const schema = {
    provider: {
        type: "sqlite"
    },
    models: {
        Foo: {
            name: "Foo",
            fields: {
                id: {
                    name: "id",
                    type: "Int",
                    id: true,
                    attributes: [{ name: "@id" }]
                },
                config: {
                    name: "config",
                    type: "Configuration",
                    attributes: [{ name: "@json" }]
                }
            },
            idFields: ["id"],
            uniqueFields: {
                id: { type: "Int" }
            }
        }
    },
    typeDefs: {
        Configuration: {
            name: "Configuration",
            fields: {
                teamColors: {
                    name: "teamColors",
                    type: "ShirtColor",
                    optional: true,
                    array: true
                }
            }
        }
    },
    enums: {
        ShirtColor: {
            Black: "Black",
            White: "White",
            Red: "Red",
            Green: "Green",
            Blue: "Blue"
        }
    },
    plugins: {}
} as const satisfies SchemaDef;
export type SchemaType = typeof schema;
