//////////////////////////////////////////////////////////////////////////////////////////////
// DO NOT MODIFY THIS FILE                                                                  //
// This file is automatically generated by ZenStack CLI and should not be manually updated. //
//////////////////////////////////////////////////////////////////////////////////////////////

/* eslint-disable */

import { type ModelResult } from "@zenstackhq/runtime";
import { schema } from "./schema";
export type Schema = typeof schema;
export type User = ModelResult<Schema, "User">;
export type Post = ModelResult<Schema, "Post">;
export type Profile = ModelResult<Schema, "Profile">;
export type Tag = ModelResult<Schema, "Tag">;
export type Region = ModelResult<Schema, "Region">;
export type Meta = ModelResult<Schema, "Meta">;
